Fix typo
carsantello/Hyperblog pull request #1
Opened 2020-10-12 22:58 UTC by carsantello

Hadn't had approved, due to some mistakes, please enhance the reviewing process for the future!

2020-10-12 23:49 UTC, carsantelo requested changes
please verify & fix the cosmetic issues

2020-10-12 23:49 UTC, carsantelo commented on blogpost.html
> +				<p> Aqui estamos verificando el apartado para realizar un merge</p>
got it, the change were cosmetic, nor functional

2020-10-12 23:49 UTC, carsantelo commented on blogpost.html
> +				<p> Aqui estamos verificando el apartado para realizar un merge</p>
Iḿ ok by proceeding with the changes, go ahead!

2020-10-13 00:00 UTC, carsantelo approved these changes
Great, everything is good so far!

2020-10-13 00:03 UTC, merged

2020-10-13 00:03 UTC, carsantello commented
left a merge by branching the emerge branch called fix-typo